/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'shortlisted' : IDL.Null,
  'reviewed' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const Application = IDL.Record({
  'id' : IDL.Nat,
  'status' : ApplicationStatus,
  'appliedAt' : Timestamp,
  'jobId' : IDL.Nat,
  'jobTitle' : IDL.Text,
  'companyName' : IDL.Text,
  'seekerPrincipal' : IDL.Principal,
});
export const ExperienceLevel = IDL.Variant({
  'mid' : IDL.Null,
  'senior' : IDL.Null,
  'entry' : IDL.Null,
});
export const WorkExperience = IDL.Record({
  'title' : IDL.Text,
  'duration' : IDL.Text,
  'company' : IDL.Text,
});
export const UpdateJobSeekerInput = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'experienceLevel' : IDL.Opt(ExperienceLevel),
  'preferredIndustries' : IDL.Vec(IDL.Text),
  'desiredSalaryMax' : IDL.Opt(IDL.Nat),
  'desiredSalaryMin' : IDL.Opt(IDL.Nat),
  'headline' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'workExperience' : IDL.Vec(WorkExperience),
  'email' : IDL.Text,
  'resumeName' : IDL.Opt(IDL.Text),
  'phone' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
  'resumeUrl' : IDL.Opt(IDL.Text),
});
export const JobSeeker = IDL.Record({
  'bio' : IDL.Opt(IDL.Text),
  'experienceLevel' : IDL.Opt(ExperienceLevel),
  'principal' : IDL.Principal,
  'preferredIndustries' : IDL.Vec(IDL.Text),
  'desiredSalaryMax' : IDL.Opt(IDL.Nat),
  'desiredSalaryMin' : IDL.Opt(IDL.Nat),
  'headline' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'workExperience' : IDL.Vec(WorkExperience),
  'email' : IDL.Text,
  'resumeName' : IDL.Opt(IDL.Text),
  'updatedAt' : Timestamp,
  'phone' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
  'resumeUrl' : IDL.Opt(IDL.Text),
});
export const JobCategory = IDL.Record({
  'id' : IDL.Nat,
  'icon' : IDL.Text,
  'name' : IDL.Text,
  'slug' : IDL.Text,
  'jobCount' : IDL.Nat,
});
export const JobStatus = IDL.Variant({
  'closed' : IDL.Null,
  'active' : IDL.Null,
});
export const JobType = IDL.Variant({
  'remote' : IDL.Null,
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const Job = IDL.Record({
  'id' : IDL.Nat,
  'status' : JobStatus,
  'experienceLevel' : ExperienceLevel,
  'title' : IDL.Text,
  'postedAt' : Timestamp,
  'responsibilities' : IDL.Text,
  'jobType' : JobType,
  'tags' : IDL.Vec(IDL.Text),
  'description' : IDL.Text,
  'qualifications' : IDL.Text,
  'isSample' : IDL.Bool,
  'isFeatured' : IDL.Bool,
  'companyLogo' : IDL.Opt(IDL.Text),
  'companyName' : IDL.Text,
  'category' : IDL.Text,
  'salaryMax' : IDL.Opt(IDL.Nat),
  'salaryMin' : IDL.Opt(IDL.Nat),
  'location' : IDL.Text,
  'industry' : IDL.Text,
  'companyId' : IDL.Nat,
});
export const SavedJob = IDL.Record({
  'jobId' : IDL.Nat,
  'jobTitle' : IDL.Text,
  'companyName' : IDL.Text,
  'savedAt' : Timestamp,
  'location' : IDL.Text,
  'seekerPrincipal' : IDL.Principal,
});
export const SortBy = IDL.Variant({
  'newest' : IDL.Null,
  'salaryHigh' : IDL.Null,
  'salaryLow' : IDL.Null,
});
export const SearchFilter = IDL.Record({
  'experienceLevel' : IDL.Opt(ExperienceLevel),
  'sortBy' : IDL.Opt(SortBy),
  'jobType' : IDL.Opt(JobType),
  'salaryMax' : IDL.Opt(IDL.Nat),
  'salaryMin' : IDL.Opt(IDL.Nat),
  'keyword' : IDL.Opt(IDL.Text),
  'location' : IDL.Opt(IDL.Text),
  'industries' : IDL.Vec(IDL.Text),
});
export const Pagination = IDL.Record({
  'total' : IDL.Nat,
  'offset' : IDL.Nat,
  'limit' : IDL.Nat,
});
export const PageResult = IDL.Record({
  'pagination' : Pagination,
  'items' : IDL.Vec(Job),
});

export const idlService = IDL.Service({
  'applyToJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
      [],
    ),
  'createOrUpdateProfile' : IDL.Func([UpdateJobSeekerInput], [JobSeeker], []),
  'getApplicationStatus' : IDL.Func(
      [IDL.Nat],
      [IDL.Opt(ApplicationStatus)],
      ['query'],
    ),
  'getCategories' : IDL.Func([], [IDL.Vec(JobCategory)], ['query']),
  'getFeaturedJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
  'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
  'getJobsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
  'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
  'getMyProfile' : IDL.Func([], [IDL.Opt(JobSeeker)], ['query']),
  'getMySavedJobs' : IDL.Func([], [IDL.Vec(SavedJob)], ['query']),
  'getRecentJobs' : IDL.Func([IDL.Nat], [IDL.Vec(Job)], ['query']),
  'getSimilarJobs' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Job)], ['query']),
  'hasApplied' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isJobSaved' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'saveJob' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : SavedJob, 'err' : IDL.Text })],
      [],
    ),
  'searchJobs' : IDL.Func([SearchFilter, Pagination], [PageResult], ['query']),
  'unsaveJob' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'shortlisted' : IDL.Null,
    'reviewed' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const Application = IDL.Record({
    'id' : IDL.Nat,
    'status' : ApplicationStatus,
    'appliedAt' : Timestamp,
    'jobId' : IDL.Nat,
    'jobTitle' : IDL.Text,
    'companyName' : IDL.Text,
    'seekerPrincipal' : IDL.Principal,
  });
  const ExperienceLevel = IDL.Variant({
    'mid' : IDL.Null,
    'senior' : IDL.Null,
    'entry' : IDL.Null,
  });
  const WorkExperience = IDL.Record({
    'title' : IDL.Text,
    'duration' : IDL.Text,
    'company' : IDL.Text,
  });
  const UpdateJobSeekerInput = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'experienceLevel' : IDL.Opt(ExperienceLevel),
    'preferredIndustries' : IDL.Vec(IDL.Text),
    'desiredSalaryMax' : IDL.Opt(IDL.Nat),
    'desiredSalaryMin' : IDL.Opt(IDL.Nat),
    'headline' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'workExperience' : IDL.Vec(WorkExperience),
    'email' : IDL.Text,
    'resumeName' : IDL.Opt(IDL.Text),
    'phone' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
    'resumeUrl' : IDL.Opt(IDL.Text),
  });
  const JobSeeker = IDL.Record({
    'bio' : IDL.Opt(IDL.Text),
    'experienceLevel' : IDL.Opt(ExperienceLevel),
    'principal' : IDL.Principal,
    'preferredIndustries' : IDL.Vec(IDL.Text),
    'desiredSalaryMax' : IDL.Opt(IDL.Nat),
    'desiredSalaryMin' : IDL.Opt(IDL.Nat),
    'headline' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'workExperience' : IDL.Vec(WorkExperience),
    'email' : IDL.Text,
    'resumeName' : IDL.Opt(IDL.Text),
    'updatedAt' : Timestamp,
    'phone' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
    'resumeUrl' : IDL.Opt(IDL.Text),
  });
  const JobCategory = IDL.Record({
    'id' : IDL.Nat,
    'icon' : IDL.Text,
    'name' : IDL.Text,
    'slug' : IDL.Text,
    'jobCount' : IDL.Nat,
  });
  const JobStatus = IDL.Variant({ 'closed' : IDL.Null, 'active' : IDL.Null });
  const JobType = IDL.Variant({
    'remote' : IDL.Null,
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const Job = IDL.Record({
    'id' : IDL.Nat,
    'status' : JobStatus,
    'experienceLevel' : ExperienceLevel,
    'title' : IDL.Text,
    'postedAt' : Timestamp,
    'responsibilities' : IDL.Text,
    'jobType' : JobType,
    'tags' : IDL.Vec(IDL.Text),
    'description' : IDL.Text,
    'qualifications' : IDL.Text,
    'isSample' : IDL.Bool,
    'isFeatured' : IDL.Bool,
    'companyLogo' : IDL.Opt(IDL.Text),
    'companyName' : IDL.Text,
    'category' : IDL.Text,
    'salaryMax' : IDL.Opt(IDL.Nat),
    'salaryMin' : IDL.Opt(IDL.Nat),
    'location' : IDL.Text,
    'industry' : IDL.Text,
    'companyId' : IDL.Nat,
  });
  const SavedJob = IDL.Record({
    'jobId' : IDL.Nat,
    'jobTitle' : IDL.Text,
    'companyName' : IDL.Text,
    'savedAt' : Timestamp,
    'location' : IDL.Text,
    'seekerPrincipal' : IDL.Principal,
  });
  const SortBy = IDL.Variant({
    'newest' : IDL.Null,
    'salaryHigh' : IDL.Null,
    'salaryLow' : IDL.Null,
  });
  const SearchFilter = IDL.Record({
    'experienceLevel' : IDL.Opt(ExperienceLevel),
    'sortBy' : IDL.Opt(SortBy),
    'jobType' : IDL.Opt(JobType),
    'salaryMax' : IDL.Opt(IDL.Nat),
    'salaryMin' : IDL.Opt(IDL.Nat),
    'keyword' : IDL.Opt(IDL.Text),
    'location' : IDL.Opt(IDL.Text),
    'industries' : IDL.Vec(IDL.Text),
  });
  const Pagination = IDL.Record({
    'total' : IDL.Nat,
    'offset' : IDL.Nat,
    'limit' : IDL.Nat,
  });
  const PageResult = IDL.Record({
    'pagination' : Pagination,
    'items' : IDL.Vec(Job),
  });
  
  return IDL.Service({
    'applyToJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : Application, 'err' : IDL.Text })],
        [],
      ),
    'createOrUpdateProfile' : IDL.Func([UpdateJobSeekerInput], [JobSeeker], []),
    'getApplicationStatus' : IDL.Func(
        [IDL.Nat],
        [IDL.Opt(ApplicationStatus)],
        ['query'],
      ),
    'getCategories' : IDL.Func([], [IDL.Vec(JobCategory)], ['query']),
    'getFeaturedJobs' : IDL.Func([], [IDL.Vec(Job)], ['query']),
    'getJob' : IDL.Func([IDL.Nat], [IDL.Opt(Job)], ['query']),
    'getJobsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Job)], ['query']),
    'getMyApplications' : IDL.Func([], [IDL.Vec(Application)], ['query']),
    'getMyProfile' : IDL.Func([], [IDL.Opt(JobSeeker)], ['query']),
    'getMySavedJobs' : IDL.Func([], [IDL.Vec(SavedJob)], ['query']),
    'getRecentJobs' : IDL.Func([IDL.Nat], [IDL.Vec(Job)], ['query']),
    'getSimilarJobs' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Job)], ['query']),
    'hasApplied' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isJobSaved' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'saveJob' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : SavedJob, 'err' : IDL.Text })],
        [],
      ),
    'searchJobs' : IDL.Func(
        [SearchFilter, Pagination],
        [PageResult],
        ['query'],
      ),
    'unsaveJob' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };