/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Application {
  'id' : bigint,
  'status' : ApplicationStatus,
  'appliedAt' : Timestamp,
  'jobId' : bigint,
  'jobTitle' : string,
  'companyName' : string,
  'seekerPrincipal' : Principal,
}
export type ApplicationStatus = { 'pending' : null } |
  { 'rejected' : null } |
  { 'shortlisted' : null } |
  { 'reviewed' : null };
export type ExperienceLevel = { 'mid' : null } |
  { 'senior' : null } |
  { 'entry' : null };
export interface Job {
  'id' : bigint,
  'status' : JobStatus,
  'experienceLevel' : ExperienceLevel,
  'title' : string,
  'postedAt' : Timestamp,
  'responsibilities' : string,
  'jobType' : JobType,
  'tags' : Array<string>,
  'description' : string,
  'qualifications' : string,
  'isSample' : boolean,
  'isFeatured' : boolean,
  'companyLogo' : [] | [string],
  'companyName' : string,
  'category' : string,
  'salaryMax' : [] | [bigint],
  'salaryMin' : [] | [bigint],
  'location' : string,
  'industry' : string,
  'companyId' : bigint,
}
export interface JobCategory {
  'id' : bigint,
  'icon' : string,
  'name' : string,
  'slug' : string,
  'jobCount' : bigint,
}
export interface JobSeeker {
  'bio' : [] | [string],
  'experienceLevel' : [] | [ExperienceLevel],
  'principal' : Principal,
  'preferredIndustries' : Array<string>,
  'desiredSalaryMax' : [] | [bigint],
  'desiredSalaryMin' : [] | [bigint],
  'headline' : [] | [string],
  'name' : string,
  'createdAt' : Timestamp,
  'workExperience' : Array<WorkExperience>,
  'email' : string,
  'resumeName' : [] | [string],
  'updatedAt' : Timestamp,
  'phone' : [] | [string],
  'location' : [] | [string],
  'resumeUrl' : [] | [string],
}
export type JobStatus = { 'closed' : null } |
  { 'active' : null };
export type JobType = { 'remote' : null } |
  { 'contract' : null } |
  { 'partTime' : null } |
  { 'fullTime' : null };
export interface PageResult { 'pagination' : Pagination, 'items' : Array<Job> }
export interface Pagination {
  'total' : bigint,
  'offset' : bigint,
  'limit' : bigint,
}
export interface SavedJob {
  'jobId' : bigint,
  'jobTitle' : string,
  'companyName' : string,
  'savedAt' : Timestamp,
  'location' : string,
  'seekerPrincipal' : Principal,
}
export interface SearchFilter {
  'experienceLevel' : [] | [ExperienceLevel],
  'sortBy' : [] | [SortBy],
  'jobType' : [] | [JobType],
  'salaryMax' : [] | [bigint],
  'salaryMin' : [] | [bigint],
  'keyword' : [] | [string],
  'location' : [] | [string],
  'industries' : Array<string>,
}
export type SortBy = { 'newest' : null } |
  { 'salaryHigh' : null } |
  { 'salaryLow' : null };
export type Timestamp = bigint;
export interface UpdateJobSeekerInput {
  'bio' : [] | [string],
  'experienceLevel' : [] | [ExperienceLevel],
  'preferredIndustries' : Array<string>,
  'desiredSalaryMax' : [] | [bigint],
  'desiredSalaryMin' : [] | [bigint],
  'headline' : [] | [string],
  'name' : string,
  'workExperience' : Array<WorkExperience>,
  'email' : string,
  'resumeName' : [] | [string],
  'phone' : [] | [string],
  'location' : [] | [string],
  'resumeUrl' : [] | [string],
}
export interface WorkExperience {
  'title' : string,
  'duration' : string,
  'company' : string,
}
export interface _SERVICE {
  'applyToJob' : ActorMethod<
    [bigint],
    { 'ok' : Application } |
      { 'err' : string }
  >,
  'createOrUpdateProfile' : ActorMethod<[UpdateJobSeekerInput], JobSeeker>,
  'getApplicationStatus' : ActorMethod<[bigint], [] | [ApplicationStatus]>,
  'getCategories' : ActorMethod<[], Array<JobCategory>>,
  'getFeaturedJobs' : ActorMethod<[], Array<Job>>,
  'getJob' : ActorMethod<[bigint], [] | [Job]>,
  'getJobsByCategory' : ActorMethod<[string], Array<Job>>,
  'getMyApplications' : ActorMethod<[], Array<Application>>,
  'getMyProfile' : ActorMethod<[], [] | [JobSeeker]>,
  'getMySavedJobs' : ActorMethod<[], Array<SavedJob>>,
  'getRecentJobs' : ActorMethod<[bigint], Array<Job>>,
  'getSimilarJobs' : ActorMethod<[bigint, bigint], Array<Job>>,
  'hasApplied' : ActorMethod<[bigint], boolean>,
  'isJobSaved' : ActorMethod<[bigint], boolean>,
  'saveJob' : ActorMethod<[bigint], { 'ok' : SavedJob } | { 'err' : string }>,
  'searchJobs' : ActorMethod<[SearchFilter, Pagination], PageResult>,
  'unsaveJob' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];