/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface Application {
    id: bigint;
    status: ApplicationStatus;
    appliedAt: Timestamp;
    jobId: bigint;
    jobTitle: string;
    companyName: string;
    seekerPrincipal: Principal;
}
export interface SearchFilter {
    experienceLevel?: ExperienceLevel;
    sortBy?: SortBy;
    jobType?: JobType;
    salaryMax?: bigint;
    salaryMin?: bigint;
    keyword?: string;
    location?: string;
    industries: Array<string>;
}
export interface JobCategory {
    id: bigint;
    icon: string;
    name: string;
    slug: string;
    jobCount: bigint;
}
export interface JobSeeker {
    bio?: string;
    experienceLevel?: ExperienceLevel;
    principal: Principal;
    preferredIndustries: Array<string>;
    desiredSalaryMax?: bigint;
    desiredSalaryMin?: bigint;
    headline?: string;
    name: string;
    createdAt: Timestamp;
    workExperience: Array<WorkExperience>;
    email: string;
    resumeName?: string;
    updatedAt: Timestamp;
    phone?: string;
    location?: string;
    resumeUrl?: string;
}
export interface SavedJob {
    jobId: bigint;
    jobTitle: string;
    companyName: string;
    savedAt: Timestamp;
    location: string;
    seekerPrincipal: Principal;
}
export interface UpdateJobSeekerInput {
    bio?: string;
    experienceLevel?: ExperienceLevel;
    preferredIndustries: Array<string>;
    desiredSalaryMax?: bigint;
    desiredSalaryMin?: bigint;
    headline?: string;
    name: string;
    workExperience: Array<WorkExperience>;
    email: string;
    resumeName?: string;
    phone?: string;
    location?: string;
    resumeUrl?: string;
}
export interface Job {
    id: bigint;
    status: JobStatus;
    experienceLevel: ExperienceLevel;
    title: string;
    postedAt: Timestamp;
    responsibilities: string;
    jobType: JobType;
    tags: Array<string>;
    description: string;
    qualifications: string;
    isSample: boolean;
    isFeatured: boolean;
    companyLogo?: string;
    companyName: string;
    category: string;
    salaryMax?: bigint;
    salaryMin?: bigint;
    location: string;
    industry: string;
    companyId: bigint;
}
export interface WorkExperience {
    title: string;
    duration: string;
    company: string;
}
export interface Pagination {
    total: bigint;
    offset: bigint;
    limit: bigint;
}
export interface PageResult {
    pagination: Pagination;
    items: Array<Job>;
}
export enum ApplicationStatus {
    pending = "pending",
    rejected = "rejected",
    shortlisted = "shortlisted",
    reviewed = "reviewed"
}
export enum ExperienceLevel {
    mid = "mid",
    senior = "senior",
    entry = "entry"
}
export enum JobStatus {
    closed = "closed",
    active = "active"
}
export enum JobType {
    remote = "remote",
    contract = "contract",
    partTime = "partTime",
    fullTime = "fullTime"
}
export enum SortBy {
    newest = "newest",
    salaryHigh = "salaryHigh",
    salaryLow = "salaryLow"
}
export interface backendInterface {
    applyToJob(jobId: bigint): Promise<{
        __kind__: "ok";
        ok: Application;
    } | {
        __kind__: "err";
        err: string;
    }>;
    createOrUpdateProfile(input: UpdateJobSeekerInput): Promise<JobSeeker>;
    getApplicationStatus(jobId: bigint): Promise<ApplicationStatus | null>;
    getCategories(): Promise<Array<JobCategory>>;
    getFeaturedJobs(): Promise<Array<Job>>;
    getJob(id: bigint): Promise<Job | null>;
    getJobsByCategory(categorySlug: string): Promise<Array<Job>>;
    getMyApplications(): Promise<Array<Application>>;
    getMyProfile(): Promise<JobSeeker | null>;
    getMySavedJobs(): Promise<Array<SavedJob>>;
    getRecentJobs(limit: bigint): Promise<Array<Job>>;
    getSimilarJobs(jobId: bigint, limit: bigint): Promise<Array<Job>>;
    hasApplied(jobId: bigint): Promise<boolean>;
    isJobSaved(jobId: bigint): Promise<boolean>;
    saveJob(jobId: bigint): Promise<{
        __kind__: "ok";
        ok: SavedJob;
    } | {
        __kind__: "err";
        err: string;
    }>;
    searchJobs(filter: SearchFilter, pagination: Pagination): Promise<PageResult>;
    unsaveJob(jobId: bigint): Promise<void>;
}
import type { Application as _Application, ApplicationStatus as _ApplicationStatus, ExperienceLevel as _ExperienceLevel, Job as _Job, JobSeeker as _JobSeeker, JobStatus as _JobStatus, JobType as _JobType, PageResult as _PageResult, Pagination as _Pagination, SavedJob as _SavedJob, SearchFilter as _SearchFilter, SortBy as _SortBy, Timestamp as _Timestamp, UpdateJobSeekerInput as _UpdateJobSeekerInput, WorkExperience as _WorkExperience } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async applyToJob(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: Application;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.applyToJob(arg0);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyToJob(arg0);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrUpdateProfile(arg0: UpdateJobSeekerInput): Promise<JobSeeker> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(to_candid_UpdateJobSeekerInput_n6(this._uploadFile, this._downloadFile, arg0));
                return from_candid_JobSeeker_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(to_candid_UpdateJobSeekerInput_n6(this._uploadFile, this._downloadFile, arg0));
            return from_candid_JobSeeker_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApplicationStatus(arg0: bigint): Promise<ApplicationStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getApplicationStatus(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApplicationStatus(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategories(): Promise<Array<JobCategory>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategories();
            return result;
        }
    }
    async getFeaturedJobs(): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeaturedJobs();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeaturedJobs();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJob(arg0: bigint): Promise<Job | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJob(arg0);
                return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJob(arg0);
            return from_candid_opt_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobsByCategory(arg0: string): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobsByCategory(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobsByCategory(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyApplications(): Promise<Array<Application>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyApplications();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyApplications();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<JobSeeker | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMySavedJobs(): Promise<Array<SavedJob>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySavedJobs();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySavedJobs();
            return result;
        }
    }
    async getRecentJobs(arg0: bigint): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecentJobs(arg0);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecentJobs(arg0);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSimilarJobs(arg0: bigint, arg1: bigint): Promise<Array<Job>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSimilarJobs(arg0, arg1);
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSimilarJobs(arg0, arg1);
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasApplied(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasApplied(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasApplied(arg0);
            return result;
        }
    }
    async isJobSaved(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isJobSaved(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isJobSaved(arg0);
            return result;
        }
    }
    async saveJob(arg0: bigint): Promise<{
        __kind__: "ok";
        ok: SavedJob;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.saveJob(arg0);
                return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveJob(arg0);
            return from_candid_variant_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchJobs(arg0: SearchFilter, arg1: Pagination): Promise<PageResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchJobs(to_candid_SearchFilter_n29(this._uploadFile, this._downloadFile, arg0), arg1);
                return from_candid_PageResult_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchJobs(to_candid_SearchFilter_n29(this._uploadFile, this._downloadFile, arg0), arg1);
            return from_candid_PageResult_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async unsaveJob(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsaveJob(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsaveJob(arg0);
            return result;
        }
    }
}
function from_candid_ApplicationStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApplicationStatus): ApplicationStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Application_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Application): Application {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_ExperienceLevel_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceLevel): ExperienceLevel {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_JobSeeker_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobSeeker): JobSeeker {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_JobStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobStatus): JobStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_JobType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobType): JobType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_Job_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Job): Job {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_PageResult_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PageResult): PageResult {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExperienceLevel]): ExperienceLevel | null {
    return value.length === 0 ? null : from_candid_ExperienceLevel_n14(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ApplicationStatus]): ApplicationStatus | null {
    return value.length === 0 ? null : from_candid_ApplicationStatus_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Job]): Job | null {
    return value.length === 0 ? null : from_candid_Job_n19(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobSeeker]): JobSeeker | null {
    return value.length === 0 ? null : from_candid_JobSeeker_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio: [] | [string];
    experienceLevel: [] | [_ExperienceLevel];
    principal: Principal;
    preferredIndustries: Array<string>;
    desiredSalaryMax: [] | [bigint];
    desiredSalaryMin: [] | [bigint];
    headline: [] | [string];
    name: string;
    createdAt: _Timestamp;
    workExperience: Array<_WorkExperience>;
    email: string;
    resumeName: [] | [string];
    updatedAt: _Timestamp;
    phone: [] | [string];
    location: [] | [string];
    resumeUrl: [] | [string];
}): {
    bio?: string;
    experienceLevel?: ExperienceLevel;
    principal: Principal;
    preferredIndustries: Array<string>;
    desiredSalaryMax?: bigint;
    desiredSalaryMin?: bigint;
    headline?: string;
    name: string;
    createdAt: Timestamp;
    workExperience: Array<WorkExperience>;
    email: string;
    resumeName?: string;
    updatedAt: Timestamp;
    phone?: string;
    location?: string;
    resumeUrl?: string;
} {
    return {
        bio: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.bio)),
        experienceLevel: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.experienceLevel)),
        principal: value.principal,
        preferredIndustries: value.preferredIndustries,
        desiredSalaryMax: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.desiredSalaryMax)),
        desiredSalaryMin: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.desiredSalaryMin)),
        headline: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.headline)),
        name: value.name,
        createdAt: value.createdAt,
        workExperience: value.workExperience,
        email: value.email,
        resumeName: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.resumeName)),
        updatedAt: value.updatedAt,
        phone: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.phone)),
        location: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.location)),
        resumeUrl: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.resumeUrl))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _JobStatus;
    experienceLevel: _ExperienceLevel;
    title: string;
    postedAt: _Timestamp;
    responsibilities: string;
    jobType: _JobType;
    tags: Array<string>;
    description: string;
    qualifications: string;
    isSample: boolean;
    isFeatured: boolean;
    companyLogo: [] | [string];
    companyName: string;
    category: string;
    salaryMax: [] | [bigint];
    salaryMin: [] | [bigint];
    location: string;
    industry: string;
    companyId: bigint;
}): {
    id: bigint;
    status: JobStatus;
    experienceLevel: ExperienceLevel;
    title: string;
    postedAt: Timestamp;
    responsibilities: string;
    jobType: JobType;
    tags: Array<string>;
    description: string;
    qualifications: string;
    isSample: boolean;
    isFeatured: boolean;
    companyLogo?: string;
    companyName: string;
    category: string;
    salaryMax?: bigint;
    salaryMin?: bigint;
    location: string;
    industry: string;
    companyId: bigint;
} {
    return {
        id: value.id,
        status: from_candid_JobStatus_n21(_uploadFile, _downloadFile, value.status),
        experienceLevel: from_candid_ExperienceLevel_n14(_uploadFile, _downloadFile, value.experienceLevel),
        title: value.title,
        postedAt: value.postedAt,
        responsibilities: value.responsibilities,
        jobType: from_candid_JobType_n23(_uploadFile, _downloadFile, value.jobType),
        tags: value.tags,
        description: value.description,
        qualifications: value.qualifications,
        isSample: value.isSample,
        isFeatured: value.isFeatured,
        companyLogo: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.companyLogo)),
        companyName: value.companyName,
        category: value.category,
        salaryMax: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.salaryMax)),
        salaryMin: record_opt_to_undefined(from_candid_opt_n16(_uploadFile, _downloadFile, value.salaryMin)),
        location: value.location,
        industry: value.industry,
        companyId: value.companyId
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _ApplicationStatus;
    appliedAt: _Timestamp;
    jobId: bigint;
    jobTitle: string;
    companyName: string;
    seekerPrincipal: Principal;
}): {
    id: bigint;
    status: ApplicationStatus;
    appliedAt: Timestamp;
    jobId: bigint;
    jobTitle: string;
    companyName: string;
    seekerPrincipal: Principal;
} {
    return {
        id: value.id,
        status: from_candid_ApplicationStatus_n4(_uploadFile, _downloadFile, value.status),
        appliedAt: value.appliedAt,
        jobId: value.jobId,
        jobTitle: value.jobTitle,
        companyName: value.companyName,
        seekerPrincipal: value.seekerPrincipal
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pagination: _Pagination;
    items: Array<_Job>;
}): {
    pagination: Pagination;
    items: Array<Job>;
} {
    return {
        pagination: value.pagination,
        items: from_candid_vec_n18(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Application;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Application;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Application_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    mid: null;
} | {
    senior: null;
} | {
    entry: null;
}): ExperienceLevel {
    return "mid" in value ? ExperienceLevel.mid : "senior" in value ? ExperienceLevel.senior : "entry" in value ? ExperienceLevel.entry : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    closed: null;
} | {
    active: null;
}): JobStatus {
    return "closed" in value ? JobStatus.closed : "active" in value ? JobStatus.active : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    remote: null;
} | {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
}): JobType {
    return "remote" in value ? JobType.remote : "contract" in value ? JobType.contract : "partTime" in value ? JobType.partTime : "fullTime" in value ? JobType.fullTime : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _SavedJob;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: SavedJob;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    rejected: null;
} | {
    shortlisted: null;
} | {
    reviewed: null;
}): ApplicationStatus {
    return "pending" in value ? ApplicationStatus.pending : "rejected" in value ? ApplicationStatus.rejected : "shortlisted" in value ? ApplicationStatus.shortlisted : "reviewed" in value ? ApplicationStatus.reviewed : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Job>): Array<Job> {
    return value.map((x)=>from_candid_Job_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Application>): Array<Application> {
    return value.map((x)=>from_candid_Application_n2(_uploadFile, _downloadFile, x));
}
function to_candid_ExperienceLevel_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): _ExperienceLevel {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_JobType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): _JobType {
    return to_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function to_candid_SearchFilter_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SearchFilter): _SearchFilter {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_SortBy_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): _SortBy {
    return to_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateJobSeekerInput_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateJobSeekerInput): _UpdateJobSeekerInput {
    return to_candid_record_n7(_uploadFile, _downloadFile, value);
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    experienceLevel?: ExperienceLevel;
    sortBy?: SortBy;
    jobType?: JobType;
    salaryMax?: bigint;
    salaryMin?: bigint;
    keyword?: string;
    location?: string;
    industries: Array<string>;
}): {
    experienceLevel: [] | [_ExperienceLevel];
    sortBy: [] | [_SortBy];
    jobType: [] | [_JobType];
    salaryMax: [] | [bigint];
    salaryMin: [] | [bigint];
    keyword: [] | [string];
    location: [] | [string];
    industries: Array<string>;
} {
    return {
        experienceLevel: value.experienceLevel ? candid_some(to_candid_ExperienceLevel_n8(_uploadFile, _downloadFile, value.experienceLevel)) : candid_none(),
        sortBy: value.sortBy ? candid_some(to_candid_SortBy_n31(_uploadFile, _downloadFile, value.sortBy)) : candid_none(),
        jobType: value.jobType ? candid_some(to_candid_JobType_n33(_uploadFile, _downloadFile, value.jobType)) : candid_none(),
        salaryMax: value.salaryMax ? candid_some(value.salaryMax) : candid_none(),
        salaryMin: value.salaryMin ? candid_some(value.salaryMin) : candid_none(),
        keyword: value.keyword ? candid_some(value.keyword) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none(),
        industries: value.industries
    };
}
function to_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bio?: string;
    experienceLevel?: ExperienceLevel;
    preferredIndustries: Array<string>;
    desiredSalaryMax?: bigint;
    desiredSalaryMin?: bigint;
    headline?: string;
    name: string;
    workExperience: Array<WorkExperience>;
    email: string;
    resumeName?: string;
    phone?: string;
    location?: string;
    resumeUrl?: string;
}): {
    bio: [] | [string];
    experienceLevel: [] | [_ExperienceLevel];
    preferredIndustries: Array<string>;
    desiredSalaryMax: [] | [bigint];
    desiredSalaryMin: [] | [bigint];
    headline: [] | [string];
    name: string;
    workExperience: Array<_WorkExperience>;
    email: string;
    resumeName: [] | [string];
    phone: [] | [string];
    location: [] | [string];
    resumeUrl: [] | [string];
} {
    return {
        bio: value.bio ? candid_some(value.bio) : candid_none(),
        experienceLevel: value.experienceLevel ? candid_some(to_candid_ExperienceLevel_n8(_uploadFile, _downloadFile, value.experienceLevel)) : candid_none(),
        preferredIndustries: value.preferredIndustries,
        desiredSalaryMax: value.desiredSalaryMax ? candid_some(value.desiredSalaryMax) : candid_none(),
        desiredSalaryMin: value.desiredSalaryMin ? candid_some(value.desiredSalaryMin) : candid_none(),
        headline: value.headline ? candid_some(value.headline) : candid_none(),
        name: value.name,
        workExperience: value.workExperience,
        email: value.email,
        resumeName: value.resumeName ? candid_some(value.resumeName) : candid_none(),
        phone: value.phone ? candid_some(value.phone) : candid_none(),
        location: value.location ? candid_some(value.location) : candid_none(),
        resumeUrl: value.resumeUrl ? candid_some(value.resumeUrl) : candid_none()
    };
}
function to_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SortBy): {
    newest: null;
} | {
    salaryHigh: null;
} | {
    salaryLow: null;
} {
    return value == SortBy.newest ? {
        newest: null
    } : value == SortBy.salaryHigh ? {
        salaryHigh: null
    } : value == SortBy.salaryLow ? {
        salaryLow: null
    } : value;
}
function to_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: JobType): {
    remote: null;
} | {
    contract: null;
} | {
    partTime: null;
} | {
    fullTime: null;
} {
    return value == JobType.remote ? {
        remote: null
    } : value == JobType.contract ? {
        contract: null
    } : value == JobType.partTime ? {
        partTime: null
    } : value == JobType.fullTime ? {
        fullTime: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): {
    mid: null;
} | {
    senior: null;
} | {
    entry: null;
} {
    return value == ExperienceLevel.mid ? {
        mid: null
    } : value == ExperienceLevel.senior ? {
        senior: null
    } : value == ExperienceLevel.entry ? {
        entry: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
